import Link from 'next/link'
import Image from 'next/image'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Plate to Pan',
  description: 'Terms of Service for the Plate to Pan iOS app and website.',
}

export default function Terms() {
  return (
    <div className="min-h-screen bg-dark-900">
      <header className="border-b border-white/5 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" aria-label="Plate2Pan home">
            <Image
              src="/branding/logo-white.png"
              alt="Plate2Pan"
              width={1630}
              height={370}
              className="h-auto w-36 opacity-90 hover:opacity-100 transition-opacity"
            />
          </Link>
          <Link href="/" className="text-sm text-white/40 hover:text-white/70 transition-colors">← Back to home</Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-black mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Effective date: January 1, 2025 · Last updated: January 1, 2025</p>

        <div className="space-y-8 text-white/70 leading-relaxed text-sm">
          <div className="glass-orange rounded-2xl p-5">
            <p className="font-semibold text-white">Pre-launch notice</p>
            <p className="mt-1">Plate2Pan is not currently available for download. These terms apply to the website now and to the app once it is released.</p>
          </div>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By downloading, installing, or using the Plate to Pan app ("App") or website ("Site"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the App or Site. These Terms are between you and Abounding Media LLC ("we," "us," "our").</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>Plate to Pan is an iOS application preparing for release that uses artificial intelligence to analyze photographs of food dishes and generate estimated recipes, including ingredients, instructions, nutrition information, and other culinary content. Once released, the App is intended to provide features including Cook Mode, meal planning, grocery list management, and pantry inventory tracking.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Important Disclaimer — Recipe Accuracy</h2>
            <p className="font-medium text-white/80">THE RECIPES GENERATED BY PLATE TO PAN ARE ESTIMATES PRODUCED BY ARTIFICIAL INTELLIGENCE AND MAY NOT BE ACCURATE.</p>
            <p className="mt-3">AI-generated recipes are best-guess approximations and may contain errors in ingredients, quantities, cooking times, temperatures, techniques, and allergen information. You use generated recipes entirely at your own risk. We strongly recommend:</p>
            <ul className="list-disc list-inside space-y-1 ml-2 mt-2">
              <li>Verifying all ingredients against your own dietary restrictions and allergies before cooking.</li>
              <li>Consulting a qualified professional for any medically required dietary needs.</li>
              <li>Using good judgment when cooking — times and temperatures are estimates.</li>
            </ul>
            <p className="mt-3">WE ARE NOT RESPONSIBLE FOR ANY ADVERSE REACTIONS, INJURY, ILLNESS, PROPERTY DAMAGE, OR OTHER HARM ARISING FROM FOLLOWING APP-GENERATED RECIPES.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Subscriptions and Payments</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Our planned launch offering includes a starter tier with 10 recipe scans at no charge.</li>
              <li>A Pro subscription (monthly or annual) is planned for unlimited scans and additional features.</li>
              <li>Once available, subscriptions will be processed through Apple App Store. All billing, refunds, and subscription management will be governed by Apple's terms.</li>
              <li>Annual subscriptions, if offered and purchased, will auto-renew unless cancelled at least 24 hours before the renewal date.</li>
              <li>A 7-day free trial may be offered at launch. You will not be charged until the trial period ends.</li>
              <li>After subscribing, you can cancel in iOS Settings → [your name] → Subscriptions → Plate to Pan.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1 ml-2 mt-2">
              <li>Attempt to reverse-engineer, decompile, or extract source code from the App.</li>
              <li>Use automated tools to submit bulk photos or scrape content from the App.</li>
              <li>Submit photos containing illegal content, nudity, or content that violates third-party rights.</li>
              <li>Share your account credentials with others or create accounts on others' behalf.</li>
              <li>Use the App in any way that violates applicable laws or regulations.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Intellectual Property</h2>
            <p>The App, its design, trademarks, and underlying technology are owned by Abounding Media LLC. You retain ownership of photos you submit. By submitting a photo, you grant us a limited, non-exclusive license to process it for the purpose of generating a recipe for you. We do not store your photos after processing.</p>
            <p className="mt-3">AI-generated recipe content is provided to you for personal, non-commercial use. You may share recipes with friends, family, or on personal social media. Commercial use or mass redistribution requires our written permission.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Disclaimer of Warranties</h2>
            <p>THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ABOUNDING MEDIA LLC BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF DATA, LOSS OF REVENUE, OR PERSONAL INJURY, ARISING FROM YOUR USE OF THE APP. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM, OR $10, WHICHEVER IS GREATER.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Governing Law</h2>
            <p>These Terms are governed by the laws of the State of Texas, United States, without regard to conflict of law principles. Any disputes shall be resolved in the state or federal courts located in Texas.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Changes to Terms</h2>
            <p>We may update these Terms at any time. We will notify you of material changes via in-app notification. Continued use after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Contact</h2>
            <div className="glass rounded-2xl p-5">
              <p className="font-semibold text-white">Abounding Media LLC</p>
              <p className="mt-1"><a href="mailto:support@plate2pan.app" className="text-brand-orange hover:underline">support@plate2pan.app</a></p>
            </div>
          </section>
        </div>
      </main>
    </div>
  )
}
